apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-secret
spec:
  replicas: {{ .Values.replica }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: init-secret
  template:
    metadata:
      labels:
        app: init-secret
    spec:
      serviceAccountName: secret-manager
      containers:
      - name: init-secret
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always

        command: ["ruby", "secrets-init.rb"]

        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"

        env:
        - name: DUMMY
          value: "001"

        - name: SECRET_NAME
          value: "initial-secret"

        - name: RUN_MODE
          value: "loop"

        securityContext:
          runAsUser: 0
