cloudflareDns1:
  zone: "please-protect.com"
  domains: "*.sensor-01.please-protect.com,*.center.please-protect.com, please-protect.com, *.please-protect.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns2:
  zone: "please-payment.com"
  domains: "*.please-payment.com, please-payment.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns3:
  zone: "please-erp.com"
  domains: "*.please-erp.com, please-erp.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns4:
  zone: "please-scan.com"
  # เอามาแแค่เว็บก่อนส่วน App ยังอยู่ที่ GCP
  domains: "web-dev.please-scan.com, please-scan.com, tenant-dev.please-scan.com, tenant.please-scan.com, verify2-dev.please-scan.com, verify2.please-scan.com, register2-dev.please-scan.com, register2.please-scan.com, scan2-dev.please-scan.com, scan2.please-scan.com, api2-dev.please-scan.com, api2.please-scan.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns5:
  zone: "dev-hubs.com"
  # เอามาแแค่เว็บก่อนส่วน App ยังอยู่ที่ GCP
  domains: "web-dev.dev-hubs.com, dev-hubs.com"
  proxied: "false"
  ip6Provider: "none"
