cloudflareDns1:
  zone: "please-protect.com"
  domains: "*.sensor-01.please-protect.com,*.center.please-protect.com, please-protect.com, *.please-protect.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns2:
  zone: "please-payment.com"
  domains: "*.please-payment.com, please-payment.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns3:
  zone: "please-erp.com"
  domains: "*.please-erp.com, please-erp.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns4:
  zone: "please-scan.com"
  # เอามาแแค่เว็บก่อนส่วน App ยังอยู่ที่ GCP
  domains: "web-dev.please-scan.com, please-scan.com"
  proxied: "false"
  ip6Provider: "none"
