cloudflareDns1:
  zone: "please-protect.com"
  domains: "*.sensor-01.please-protect.com,*.center.please-protect.com, please-protect.com, *.please-protect.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns2:
  zone: "please-payment.com"
  domains: "*.please-payment.com, please-payment.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns3:
  zone: "please-erp.com"
  domains: "*.please-erp.com, please-erp.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns4:
  zone: "please-scan.com"
  domains: "web-dev.please-scan.com, please-scan.com, console-dev.please-scan.com, console.please-scan.com, verify-dev.please-scan.com, verify.please-scan.com, register-dev.please-scan.com, register.please-scan.com, scan-dev.please-scan.com, scan.please-scan.com, api-dev.please-scan.com, api.please-scan.com, admin-dev.please-scan.com, admin.please-scan.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns5:
  zone: "dev-hubs.com"
  domains: "web-dev.dev-hubs.com, dev-hubs.com"
  proxied: "false"
  ip6Provider: "none"

cloudflareDns6:
  zone: "wintech-thai.com"
  domains: "sgl.wintech-thai.com, nap.wintech-thai.com, aldamex.wintech-thai.com, napbiotec.wintech-thai.com, youngyou.wintech-thai.com, sandbox.wintech-thai.com"
  proxied: "true"
  ip6Provider: "none"
