#### DevHubs Web
devHubsWebProd:
  service:
    name: dh-web-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: dh-web-proxy-prod
    vhost: web-prod.dev-hubs.local
    host: dev-hubs.com

devHubsWebDev:
  service:
    name: dh-web-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: dh-web-proxy-dev
    vhost: web-dev.dev-hubs.local
    host: web-dev.dev-hubs.com


#### Please Scan Web
psWebProd:
  service:
    name: ps-web-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-web-proxy-prod
    vhost: web-prod.please-scan.local
    host: please-scan.com

psWebDev:
  service:
    name: ps-web-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-web-proxy-dev
    vhost: web-dev.please-scan.local
    host: web-dev.please-scan.com

psTenantProd:
  service:
    name: ps-tenant-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-tenant-proxy-prod
    vhost: tenant-prod.please-scan.local
    host: tenant.please-scan.com

psTenantDev:
  service:
    name: ps-tenant-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-tenant-proxy-dev
    vhost: tenant-dev.please-scan.local
    host: tenant-dev.please-scan.com

psVerifyProd:
  service:
    name: ps-verify-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-verify-proxy-prod
    vhost: verify-prod.please-scan.local
    host: verify2.please-scan.com

psVerifyDev:
  service:
    name: ps-verify-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-verify-proxy-dev
    vhost: verify-dev.please-scan.local
    host: verify2-dev.please-scan.com

psRegisterProd:
  service:
    name: ps-register-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-register-proxy-prod
    vhost: register-prod.please-scan.local
    host: register2.please-scan.com

psRegisterDev:
  service:
    name: ps-register-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-register-proxy-dev
    vhost: register-dev.please-scan.local
    host: register2-dev.please-scan.com

psScanProd:
  service:
    name: ps-scan-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-scan-proxy-prod
    vhost: scan-prod.please-scan.local
    host: scan2.please-scan.com

psScanDev:
  service:
    name: ps-scan-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-scan-proxy-dev
    vhost: scan-dev.please-scan.local
    host: scan2-dev.please-scan.com

psApiProd:
  service:
    name: ps-api-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-api-proxy-prod
    vhost: api-prod.please-scan.local
    host: api2.please-scan.com

psApiDev:
  service:
    name: ps-api-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-api-proxy-dev
    vhost: api-dev.please-scan.local
    host: api2-dev.please-scan.com

psAdminDev:
  service:
    name: ps-admin-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-admin-proxy-dev
    vhost: admin-dev.please-scan.local
    host: admin-dev.please-scan.com

psAdminProd:
  service:
    name: ps-admin-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: ps-admin-proxy-prod
    vhost: admin-prod.please-scan.local
    host: admin-prod.please-scan.com

#### Please Protect Web
ppWebProd:
  service:
    name: pp-web-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: pp-web-proxy-prod
    vhost: web-prod.please-protect.local
    host: please-protect.com

ppWebDev:
  service:
    name: pp-web-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: pp-web-proxy-dev
    vhost: web-dev.please-protect.local
    host: web-dev.please-protect.com


ppSensorApiDev:
  service:
    name: sensor-api-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.11
  ingress:
    name: sensor-api-proxy-dev
    vhost: api-dev.sensor.local
    host: api-dev.sensor-01.please-protect.com

ppSensorWebDev:
  service:
    name: sensor-web-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.11
  ingress:
    name: sensor-web-proxy-dev
    vhost: web-dev.sensor.local
    host: web-dev.sensor-01.please-protect.com

ppSensorApiProd: {} # No API in production yet, but we want to keep the structure consistent for when we do have one.

ppSensorWebProd:
  service:
    name: sensor-web-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.11
  ingress:
    name: sensor-web-proxy-prod
    vhost: web.sensor.local
    host: web.sensor-01.please-protect.com

ppCenterOpenCTI:
  service:
    name: center-opencti-upstream
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-opencti-proxy
    vhost: opencti.pp-center.local
    host: opencti.center.please-protect.com

ppCenterWebProd:
  service:
    name: center-web-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-web-proxy-prod
    vhost: center-prod.pp-center.local
    host: web.center.please-protect.com

ppCenterWebDev:
  service:
    name: center-web-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-web-proxy-dev
    vhost: center-dev.pp-center.local
    host: web-dev.center.please-protect.com

ppCenterApiProd:
  service:
    name: center-api-upstream-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-api-proxy-prod
    vhost: api-prod.pp-center.local
    host: api.center.please-protect.com

ppCenterApiDev:
  service:
    name: center-api-upstream-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-api-proxy-dev
    vhost: api-dev.pp-center.local
    host: api-dev.center.please-protect.com

ppCenterDownloads:
  service:
    name: center-downloads-upstream
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: center-downloads-proxy
    vhost: downloads.pp-center.local
    host: downloads.center.please-protect.com



### Please ERP ###
pleaseErpAdminDev:
  service:
    name: please-erp-admin-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-erp-admin-dev
    vhost: admin-dev.please-erp.local
    host: admin-dev.please-erp.com

pleaseErpAdminProd:
  service:
    name: please-erp-admin-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-erp-admin-prod
    vhost: admin-prod.please-erp.local
    host: admin.please-erp.com

pleaseErpTenantDev:
  service:
    name: please-erp-tenant-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-erp-tenant-dev
    vhost: tenant-dev.please-erp.local
    host: tenant-dev.please-erp.com

pleaseErpTenantProd:
  service:
    name: please-erp-tenant-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-erp-tenant-prod
    vhost: tenant-prod.please-erp.local
    host: tenant.please-erp.com

pleaseErpApiDev:
  service:
    name: please-erp-api-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-erp-api-dev
    vhost: api-dev.please-erp.local
    host: api-dev.please-erp.com



### Please Payment ###
pleasePaymentAdminDev:
  service:
    name: please-payment-admin-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-admin-dev
    vhost: admin-dev.please-payment.local
    host: admin-dev.please-payment.com

pleasePaymentAdminProd:
  service:
    name: please-payment-admin-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-admin-prod
    vhost: admin-prod.please-payment.local
    host: admin.please-payment.com

pleasePaymentMerchantDev:
  service:
    name: please-payment-merchant-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-merchant-dev
    vhost: merchant-dev.please-payment.local
    host: merchant-dev.please-payment.com

pleasePaymentMerchantProd:
  service:
    name: please-payment-merchant-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-merchant-prod
    vhost: merchant-prod.please-payment.local
    host: merchant.please-payment.com

pleasePaymentWebDev:
  service:
    name: please-payment-web-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-web-dev
    vhost: web-dev.please-payment.local
    host: web-dev.please-payment.com

pleasePaymentWebProd:
  service:
    name: please-payment-web-prod
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-web-prod
    vhost: web-prod.please-payment.local
    host: please-payment.com

pleasePaymentApiDev:
  service:
    name: please-payment-api-dev
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: please-payment-api-dev
    vhost: api-dev.please-payment.local
    host: api-dev.please-payment.com

minIoApi:
  service:
    name: minio-api
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: minio-api
    vhost: storage-api.please-payment.local
    host: storage-api.please-payment.com

minIoConsole:
  service:
    name: minio-console
    port: 443
  endpoints:
    ip: 192.168.1.13
  ingress:
    name: minio-console
    vhost: storage-console.please-payment.local
    host: storage-console.please-payment.com
