---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ppCenterApiDev.service.name }}
spec:
  ports:
    - port: {{ .Values.ppCenterApiDev.service.port }}
      targetPort: {{ .Values.ppCenterApiDev.service.port }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.ppCenterApiDev.service.name }}
subsets:
  - addresses:
      - ip: {{ .Values.ppCenterApiDev.endpoints.ip }}
    ports:
      - port: {{ .Values.ppCenterApiDev.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ppCenterApiDev.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .Values.ppCenterApiDev.ingress.vhost }}"
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "{{ .Values.ppCenterApiDev.ingress.vhost }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.ppCenterApiDev.ingress.host }}
  rules:
    - host: {{ .Values.ppCenterApiDev.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ppCenterApiDev.service.name }}
                port:
                  number: {{ .Values.ppCenterApiDev.service.port }}
