---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ppSensorApiDev.service.name }}
spec:
  ports:
    - port: {{ .Values.ppSensorApiDev.service.port }}
      targetPort: {{ .Values.ppSensorApiDev.service.port }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.ppSensorApiDev.service.name }}
subsets:
  - addresses:
      - ip: {{ .Values.ppSensorApiDev.endpoints.ip }}
    ports:
      - port: {{ .Values.ppSensorApiDev.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ppSensorApiDev.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .Values.ppSensorApiDev.ingress.vhost }}"
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "{{ .Values.ppSensorApiDev.ingress.vhost }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ppSensorApiDev.ingress.host }}
      secretName: {{ .Values.ppSensorApiDev.ingress.name }}
  rules:
    - host: {{ .Values.ppSensorApiDev.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ppSensorApiDev.service.name }}
                port:
                  number: {{ .Values.ppSensorApiDev.service.port }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ppSensorApiDev.ingress.name }}
spec:
  secretName: {{ .Values.ppSensorApiDev.ingress.name }}
  dnsNames:
    - {{ .Values.ppSensorApiDev.ingress.host }}
  issuerRef:
    name: lets-encrypt-dns
    kind: ClusterIssuer
    group: cert-manager.io
