apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-k8s-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /tools/grafana-k8s
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-crds-grafana
                port:
                  number: 80
