apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns
data:
  DOMAINS: "{{ .Values.cloudflareDns.domains }}"
  PROXIED: "{{ .Values.cloudflareDns.proxied }}"
  IP6_PROVIDER: "{{ .Values.cloudflareDns.ip6Provider }}"
  ZONE: "{{ .Values.cloudflareDns.zone }}"
