apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: cloudflare-ddns       # name of the k8s Secret to be created
  data:
  - secretKey: API_TOKEN
    remoteRef:
      key: initial-secret
      property: CF_DNS_API_KEY
