apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'monitoring-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/please-protect-cti-data-plane.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/monitoring'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: monitoring
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
